name: geoflood
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - gdal
  - pip
  - numpy
  - rtree
  - numba
  - pandas
  - geopandas
  - tqdm
  - richdem
  - rasterio
  - rasterstats
